# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Menu:
  fields:
    default: name, club_id
    form: name, club_id
  order_by: 
  relationships: 
  filters: created_at
  search: name
  application: admin-typos

